Gamming/RPV-G2-Gamming2/src/main/java/com/rpvg2/control/ItemPautaController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpvg2.control;

/**
 *
 * @author victorqribeiro
 */
import com.rpvg2.model.ItemPauta;
import com.rpvg2.model.Relator;
import com.rpvg2.model.repository.ItemPautaRepository;
import com.rpvg2.model.repository.RelatorRepository;
import com.rpvg2.util.StringUtil;
import com.rpvg2.view.MensagensView;
import java.io.IOException;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

@ManagedBean
@SessionScoped
public class ItemPautaController implements Serializable {

    private List<ItemPauta> listaItensPauta;
    private MensagensView mensagensView;
    private ItemPautaRepository itemPautaREP;
    private RelatorRepository relatorREP;
    private ItemPauta itemPautaSelecionado = new ItemPauta();
    private String descReuniao;
    private String descItemPauta;
    private String relator;

    public ItemPautaController() {
        this.listaItensPauta = new ArrayList();
        this.itemPautaREP = new ItemPautaRepository();
        this.mensagensView = new MensagensView();
        this.relatorREP = new RelatorRepository();
    }

    public void selectBancoDeDados() {
        try {
            this.listaItensPauta = this.itemPautaREP.recuperarPorReuniao(descReuniao);
        } catch (SQLException ex) {
            this.mensagensView.criarMensagemError(ex.getMessage());
        } catch (ClassNotFoundException ex) {
            this.mensagensView.criarMensagemError(ex.getMessage());
        }
    }

    public void salvarNovoItemPauta() {
        try {
            if (!StringUtil.verificaStringVazia(descItemPauta) && !StringUtil.verificaStringVazia(relator)) {
                //chamar a repository
                ItemPauta aux = itemPautaREP.inserirObjetoItemPauta(descItemPauta, relator, descReuniao);
                relator = "";
                descItemPauta = "";

                //adicionar o item de pauta criado na lista de intens de pauta
                listaItensPauta.add(aux);
                this.mensagensView.criarMensagemInfo("Item de Pauta criado com sucesso!");
            } else {
                this.mensagensView.criarMensagemWarn("Verifique se todas as informações foram inseridas corretamente!");
            }
        } catch (Exception e) {
            this.mensagensView.criarMensagemError(e.getMessage());
        }
    }

    public List<String> completeText(String query) {
        List<String> relatores = new ArrayList<>();
        List<Relator> result = new ArrayList<>();
        try {
            if (!query.trim().isEmpty() && query != null) {
                result = new RelatorRepository().recuperarTodosObjetos();
                for (Relator relator : result) {
                    if (relator.getNome().toLowerCase().contains(query.toLowerCase())) {
                        relatores.add(relator.getNome());
                    }
                }
            }

        } catch (SQLException | ClassNotFoundException ex) {
            new MensagensView().criarMensagemError(ex.getMessage());
        }
        return relatores;
    }

    public void deletarItemPauta(ItemPauta itemPauta) {
        try {
            itemPautaREP.excluirObjeto(itemPauta);
            listaItensPauta.remove(itemPauta);
            this.mensagensView.criarMensagemInfo("Item Pauta excluido com sucesso!!");
        } catch (SQLException | ClassNotFoundException ex) {
            this.mensagensView.criarMensagemError(ex.getMessage());
        }
    }

    public void atualizarItemPauta() throws IOException {
        if (itemPautaSelecionado == null) {
            this.mensagensView.criarMensagemWarn("Nenhum item de pauta selecionado!");
            return;
        }

        try {
            //passar como parametro tambem os novos dados
            if (!StringUtil.verificaStringVazia(descItemPauta) && !StringUtil.verificaStringVazia(relator)) {
                if (!relator.equalsIgnoreCase(itemPautaSelecionado.getRelator().getNome())) {
                    try {
                        Relator r = (Relator) this.relatorREP.recuperarPorDescricao(relator).get(0);
                        itemPautaSelecionado.setRelator(r);
                    } catch (Exception e) {
                        this.mensagensView.criarMensagemWarn("Relator não cadastrado no sistema!");
                        return;
                    }
                }

                if (!descItemPauta.equalsIgnoreCase(itemPautaSelecionado.getDescricao())) {
                    itemPautaSelecionado.setDescricao(descItemPauta);
                }

                itemPautaREP.editarObjetoItemPauta(itemPautaSelecionado, descReuniao);
                itemPautaSelecionado = null;

                FacesContext.getCurrentInstance().getExternalContext().redirect("edicaoitensreuniao.xhtml");
                this.mensagensView.criarMensagemInfo("Editado com sucesso!!");
            } else {
                this.mensagensView.criarMensagemWarn("Verifique se todas as informações foram inseridas corretamente!");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            this.mensagensView.criarMensagemError(ex.getMessage());
        }
    }

    public void setItemPautaSelecionado(ItemPauta itemPautaSelecionado) throws IOException {
        this.itemPautaSelecionado = itemPautaSelecionado;
        this.descItemPauta = itemPautaSelecionado.getDescricao();
        this.relator = itemPautaSelecionado.getRelator().getNome();

        FacesContext.getCurrentInstance().getExternalContext().redirect("editaitempautav2.xhtml");
    }

    public String getMensagemEdicaoPersonalizada() {
        return "<strong>Dados Antigos</strong>"
                + "<br/>" + itemPautaSelecionado.getDescricao() + " - " + itemPautaSelecionado.getRelator().getNome()
                + "<br/><br/><strong>Dados Novos</strong>"
                + "<br/>" + descItemPauta + " - " + relator;
    }

    public void limparCampos() {
        this.relator = "";
        this.descItemPauta = "";
    }

//<editor-fold defaultstate="collapsed" desc="Gets e Sets">
    public List<ItemPauta> getListaItensPauta() {
        return listaItensPauta;
    }

    public void setListaItensPauta(List<ItemPauta> listaItensPauta) {
        this.listaItensPauta = listaItensPauta;
    }

    public String getDescReuniao() {
        return descReuniao;
    }

    public void setDescReuniao(String descReuniao) {
        this.descReuniao = descReuniao;
    }

    public String getDescItemPauta() {
        return descItemPauta;
    }

    public void setDescItemPauta(String descItemPauta) {
        this.descItemPauta = descItemPauta;
    }

    public String getRelator() {
        return relator;
    }

    public void setRelator(String relator) {
        this.relator = relator;
    }

    public ItemPauta getItemPautaSelecionado() {
        return itemPautaSelecionado;
    }

//</editor-fold>
}

Gamming/RPV-G2-Gamming2/src/main/webapp/secretario/autocomplete.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <p:outputLabel for="autorelator" value="Relator: "/>
            <p:autoComplete value="#{autoCompleteView.relator}" id="autorelator" var ="relator" itemLabel="#{relator.nome}" itemValue="#{relator}" completeMethod="#{autoCompleteView.completeText}" required="true" forceSelection="true"/>.
        </h:form>
    </h:body>
</html>

Gamming/RPV-G2-Gamming2/src/main/webapp/secretario/edicaoitensreuniao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>Pautas</title> 
        <link rel="shortcut icon" href="../img/favicon.png" type="image/x-png"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="stylesheet" href="../css/estilo_moderador.css" />
        <f:metadata>
            <f:viewParam name="reuniaoDesc" value="#{itemPautaController.descReuniao}" />
        </f:metadata>
    </h:head> 
    <h:body>
        #{itemPautaController.selectBancoDeDados()}
        #{itemPautaController.limparCampos()}
        <p:panel>
            <p:growl id="msg" showDetail="true" sticky="true" />
            <h:form>
                <p:confirmDialog id="global" global="true" showEffect="fade" hideEffect="fade" >
                    <p:commandButton value="Sim" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                    <p:commandButton value="Não" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                </p:confirmDialog>
                <p:menubar style="float:right">
                    <p:menuitem value="User" icon="fa fa-user" url="#"/>
                    <p:menuitem value="Sair" icon="fa fa-sign-out" url="../"/>
                </p:menubar>
            </h:form>
            <div id="header">
                <div><img src="../img/unipampa.png" id="logo"/></div>
                <div id="logo_texto">Sistema de Votação Online</div>
            </div>
            <div class="breadCrumb">
                <ul>
                    <li><a href="../home.xhtml">Home</a></li>
                    <li><a href="selecaoreuniaosec.xhtml">Reuniões</a></li>
                    <li><a href="#">Gerenciamento de Pautas</a></li>
                </ul>
            </div>
            <p:separator/>
            <p:panel header="Alerando Itens de Pauta da Reunião: #{itemPautaController.descReuniao}">
                <p:panel header="Adicionar Novo Item de Pauta">
                    <h:form>
                        <h:panelGrid columns="2">
                            <p:outputLabel for="desc" value="Descrição: "/>
                            <p:inputTextarea id="desc" rows="2" cols="45" required="True" value="#{itemPautaController.descItemPauta}" requiredMessage="A descrição não pode estar vazia!"/>
                            <p:outputLabel for="relator" value="Relator: "/>
                            <p:autoComplete id="relator" size="35" value="#{itemPautaController.relator}" var ="nome" itemLabel="#{nome}" itemValue="#{nome}" completeMethod="#{itemPautaController.completeText}" required="true" forceSelection="true"/>
                        </h:panelGrid> 
                        <p:commandButton value="Registrar Item de Pauta" icon="fa fa-plus" update="msg,listaPautas,relator,desc" actionListener="#{itemPautaController.salvarNovoItemPauta()}"/>
                    </h:form>
                </p:panel>

                <p:separator/>
                <p:panel id="listaPautas" header="Itens de Pauta Cadastrados">
                    <h:form>
                        <p:dataTable  emptyMessage="Essa reunião não possui itens pauta cadastrados" var="itemPauta" value="#{itemPautaController.listaItensPauta}" draggableRows="true" >
                            <p:column headerText="Descrição">
                                <h:outputText value="#{itemPauta.descricao}" />
                            </p:column>

                            <p:column headerText="Relator">
                                <h:outputText value="#{itemPauta.relator.nome}" />
                            </p:column>

                            <p:column headerText="Editar Item de Pauta">
                                <p:commandButton value="Excluir" icon="fa fa-trash" actionListener="#{itemPautaController.deletarItemPauta(itemPauta)}" update="msg,listaPautas">
                                    <p:confirm header="Confirme a exclução do item de pauta" message="#{itemPauta.descricao} - #{itemPauta.relator.nome}" icon="ui-icon-alert"/>
                                </p:commandButton>
                                <p:commandButton value="Editar" icon="fa fa-edit" actionListener="#{itemPautaController.setItemPautaSelecionado(itemPauta)}" update="msg,listaPautas"/>
                            </p:column>
                        </p:dataTable>
                    </h:form>
                </p:panel>
            </p:panel>
            <p:separator/>
        </p:panel>
    </h:body>
</html>

Gamming/RPV-G2-Gamming2/src/main/webapp/secretario/editaitempauta.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Pautas</title> 
        <link rel="shortcut icon" href="../img/favicon.png" type="image/x-png"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="stylesheet" href="../css/estilo_moderador.css" />
    </h:head>
    <h:body>
        <p:panel>
            <h:form>
                <p:menubar style="float:right">
                    <p:menuitem value="User" icon="fa fa-user" url="#"/>
                    <p:menuitem value="Sair" icon="fa fa-sign-out" url="../"/>
                </p:menubar>
            </h:form>
            <div id="header">
                <div><img src="../img/unipampa.png" id="logo"/></div>
                <div id="logo_texto">Sistema de Votação Online</div>
            </div>
            <div class="breadCrumb">
                <ul>
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Reuniões</a></li>
                    <li><a href="#">Gerenciamento de Pautas</a></li>
                    <li><a href="#">Editanto Pauta</a></li>
                </ul>
            </div>
            <p:separator/>
            <p:panel>
                <h:form>
                    <p:growl id="msg" showDetail="true" sticky="true" />

                    <h:panelGrid columns="1" cellpadding="5" >
                        <h:column>
                            <p:separator/>
                            <p:outputPanel><strong>Informações Antigas</strong></p:outputPanel>
                            <p:separator/>
                            <h:panelGrid columns="2" cellpadding="5">
                                <p:outputLabel>Descrição: #{itemPautaController.itemPautaSelecionado.descricao}</p:outputLabel>
                                <p:outputLabel>Relator: #{itemPautaController.itemPautaSelecionado.relator.nome}</p:outputLabel>
                            </h:panelGrid>    
                        </h:column>
                        <h:column>
                            <p:separator/>
                            <p:outputPanel><strong>Informações Novas</strong></p:outputPanel>
                            <p:separator/>
                            <h:panelGrid columns="4" cellpadding="5">
                                <p:outputLabel>Descrição: </p:outputLabel>
                                <p:inputText style="margin-right: 10px"></p:inputText>
                                <p:outputLabel>Relator: </p:outputLabel>
                                <p:inputText></p:inputText>
                            </h:panelGrid>    
                        </h:column>
                    </h:panelGrid>
                    <p:commandButton value="Salvar" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check">
                        <p:confirm header="Confirmar Criação" message="Descrição Antiga: Nova Descrição:  Relator Antigo:  Novo Relator:" escape="false" />
                    </p:commandButton>
                    <p:commandButton value="Cancelar" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close">
                        <p:confirm header="Cancelar" message="Cancelar edição do Item de Pauta" escape="false" />
                    </p:commandButton>

                    <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                        <p:commandButton value="Sim" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                        <p:commandButton value="Não" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                    </p:confirmDialog>
                </h:form>
            </p:panel>
            <p:separator/>
        </p:panel>
    </h:body>
</html>

Gamming/RPV-G2-Gamming2/src/main/webapp/secretario/editaitempautav2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Pautas</title> 
        <link rel="shortcut icon" href="../img/favicon.png" type="image/x-png"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="stylesheet" href="../css/estilo_moderador.css" />
    </h:head>
    <h:body>
        <p:panel>
            <h:form>
                <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                    <p:commandButton value="Sim" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                    <p:commandButton value="Não" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                </p:confirmDialog>
                <p:menubar style="float:right">
                    <p:menuitem value="User" icon="fa fa-user" url="#"/>
                    <p:menuitem value="Sair" icon="fa fa-sign-out" url="../"/>
                </p:menubar>
            </h:form>
            <div id="header">
                <div><img src="../img/unipampa.png" id="logo"/></div>
                <div id="logo_texto">Sistema de Votação Online</div>
            </div>
            <div class="breadCrumb">
                <ul>
                    <li><a href="../home.xhtml">Home</a></li>
                    <li><a href="selecaoreuniaosec.xhtml">Reuniões</a></li>
                    <li><a href="edicaoitensreuniao.xhtml">Gerenciamento de Pautas</a></li>
                    <li><a href="#">Editanto Pauta</a></li>
                </ul>
            </div>
            <p:separator/>
            <p:panel>
                <h:form>
                    <p:growl id="msg" showDetail="true" sticky="true" />
                    <p:outputPanel><strong>Editar o Item de Pauta</strong></p:outputPanel>
                    <p:separator/>
                    <h:panelGrid columns="4" cellpadding="5" >
                        <p:outputLabel for="desc">Descrição: </p:outputLabel>
                        <p:inputTextarea id="desc" rows="1" cols="45" style="margin-right: 10px" value="#{itemPautaController.descItemPauta}">       
                            <p:ajax event="change" update="confirmdialog" />
                        </p:inputTextarea>
                        <p:outputLabel for="relator" >Relator: </p:outputLabel>  
                        <p:autoComplete  value="#{itemPautaController.relator}" id="relator" var ="nome" itemLabel="#{nome}" itemValue="#{nome}" completeMethod="#{itemPautaController.completeText}" required="true" forceSelection="true">
                            <p:ajax event="change" update="confirmdialog" />
                            <p:ajax event="blur" update="confirmdialog" />
                        </p:autoComplete>

                    </h:panelGrid>
                    <p:commandButton id="confirmdialog" value="Salvar" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" actionListener="#{itemPautaController.atualizarItemPauta()}">
                        <p:confirm  header="Confirmar Edição" message="#{itemPautaController.mensagemEdicaoPersonalizada}" escape="false" />
                    </p:commandButton>

                    <p:commandButton value="Cancelar" styleClass="ui-confirmdialog-no" icon="ui-icon-close" action="edicaoitensreuniao">
                        <p:confirm header="Cancelar" message="Cancelar edição do Item de Pauta?" escape="false" />
                    </p:commandButton>
                </h:form>
            </p:panel>
            <p:separator/>
        </p:panel>
    </h:body>
</html>

Gamming/RPV-G2-Gamming2/src/main/webapp/secretario/selecaoreuniaosec.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>Reuniões</title> 
        <link rel="shortcut icon" href="../img/favicon.png" type="image/x-png"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="stylesheet" href="../css/estilo_moderador.css" />
    </h:head> 
    <h:body>
        #{reuniaoController.selectReunioesSec(autenticacaoController.user)}
        <p:panel>
            <h:form>
                <p:menubar style="float:right">
                    <p:menuitem value="User" icon="fa fa-user" url="#"/>
                    <p:menuitem value="Sair" icon="fa fa-sign-out" url="../"/>
                </p:menubar>
            </h:form>
            <div id="header">
                <div><img src="../img/unipampa.png" id="logo"/></div>
                <div id="logo_texto">Sistema de Votação Online</div>
            </div>
            <div class="breadCrumb">
                <ul>
                    <li><a href="../home.xhtml">Home</a></li>
                    <li><a href="#">Reuniões</a></li>
                </ul>
            </div>
            <p:growl id="msg" showDetail="true" sticky="true"/>
            <p:separator/>
            <h:form>
                <p:panel header="Selecione a reunião que deseja editar">
                    <p:orderList value="#{reuniaoController.reunioes}" var="reuniao" controlsLocation="none" itemValue="#{reuniao}" responsive="true">
                        <f:facet name="caption">Reuniões</f:facet>
                        <p:column>
                            <p:link outcome="edicaoitensreuniao" value="#{reuniao.descricao}">
                                <f:param name="reuniaoDesc" value="#{reuniao.descricao}" />
                            </p:link>
                        </p:column>
                    </p:orderList>
                </p:panel>
            </h:form>
            <p:separator/>
        </p:panel>
    </h:body>
</html>